version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - ".github/**/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "shogo452"
    target-branch: "main"
    labels:
      - "dependabot"
