name: 'Setup GitHub CLI for CodeBuild-hosted GitHub Actions runner'
author: "shogo452"
description: 'Action to install GitHub CLI for CodeBuild-hosted GitHub Actions runner'

branding:
  icon: 'arrow-down'
  color: 'blue'

inputs:
  GH_VERSION:
    description: 'GitHub CLI version (optional, latest version will be used if not specified)'
    required: false
    default: ''
  ARCH:
    description: 'Architecture'
    required: true
    default: amd64
runs:
  using: composite
  steps:
    - name: Install GitHub CLI
      shell: bash
      env:
        GH_VERSION: ${{ inputs.GH_VERSION }}
        ARCH: ${{ inputs.ARCH }}
      run: |
        # Get the version number
        if [ -z "$GH_VERSION" ]; then
          echo "No version specified, fetching latest release version..."
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/cli/cli/releases" | \
            grep -Po '"tag_name": "v\K[0-9]+\.[0-9]+\.[0-9]+(?=")' | \
            grep -vE "(rc|alpha|beta|preview)" | \
            head -n1)

          if [ -z "$LATEST_VERSION" ]; then
            echo "Failed to fetch latest stable version"
            exit 1
          fi
          GH_VERSION=$LATEST_VERSION
          echo "Latest stable version: $GH_VERSION"
        fi

        # Validate version number
        if ! [[ $GH_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version number: $GH_VERSION"
          exit 1
        fi

        # Validate architecture
        valid_archs=("amd64" "arm64")
        if ! [[ "${valid_archs[@]}" =~ "${ARCH}" ]]; then
          echo "Invalid architecture: $ARCH"
          exit 1
        fi

        # Download and extract gh
        DOWNLOAD_URL="https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_${ARCH}.tar.gz"
        EXTRACT_DIR="gh_${GH_VERSION}_linux_${ARCH}"
        wget "$DOWNLOAD_URL" -P /tmp
        tar -xzf "/tmp/gh_${GH_VERSION}_linux_${ARCH}.tar.gz" -C /tmp
        mkdir -p /tmp/gh-cli
        cp "/tmp/${EXTRACT_DIR}/bin/gh" /tmp/gh-cli/
        chmod +x /tmp/gh-cli/gh
        echo "/tmp/gh-cli" >> $GITHUB_PATH

    - name: Check gh version
      shell: bash
      run: |
        gh version
