name: Assign Author

on:
  pull_request:
    types: opened
    branches: main

jobs:
  assign_author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: `${{ github.actor }}`
            });
